---
- name: fstrim weekly cronjob.
  copy:
    dest: /etc/cron.weekly/fstrim
    content: |
      #!/bin/sh
      LOG=/var/log/fstrim.log
      echo "*** $(date -R) ***" >> $LOG
      fstrim -v -a >> $LOG
    owner: root
    group: root
    mode: o=rwx

- name: enable udev fstrim rules for usb massstorage.
  template:
    dest: /etc/udev/rules.d/10-trim_umap.rules
    src: etc/udev/rules.d/10-trim_umap.rules.j2
    mode: 0644

  when:
    - pve_fstrim_usb_id_vendor is defined
    - pve_fstrim_usb_id_product is defined
