---
- name: "Ensure /etc/pve/priv/ldap dir exists"
  file:
    path: "/etc/pve/priv/ldap"
    state: directory
    mode: 0700

- name: "Ensure password file exists."
  file:
    path: "/etc/pve/priv/ldap/{{ item.name }}.pw"
    state: touch
    mode: 0600
  changed_when: false

- name: "Provision bind password for {{ item.name }}."
  copy:
    content: "{{ item.password }}"
    dest: "/etc/pve/priv/ldap/{{ item.name }}.pw"
    mode: 0600
  notify:
    - restart pveproxy

- name: "Ensure domains.cfg is present."
  file:
    state: touch
    path: /etc/pve/domains.cfg
    mode: 0600

- name: "Provision domains.cfg"
  blockinfile:
    path: /etc/pve/domains.cfg
    marker: "\n# {mark} {{ item.name }} LDAP ANSIBLE MANAGED BLOCK"
    create: yes
    block: |
      ldap: {{ item.name }}
              comment {{ item.name }} LDAP
              base_dn {{ item.base_dn }}
              server1 {{ item.server }}
              user_attr {{ item.user_attr }}
              default {{ item.default }}
              secure {{ item.secure }}
              bind_dn {{ item.bind_dn }}
    mode: 0600
  notify:
    - restart pveproxy
