---
- name: Remove enterprise subscription lists.
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/{{ item }}"
    state: absent
  with_items:
    - pve-enterprise.list.dpkg-dist
    - pve-enterprise.list
    - ceph.list
  tags:
    - apt

- name: Create no subscription update list.
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/pve-no-subscription.list
    content: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
    mode: "0644"
  tags:
    - apt

- name: Install pve-headers.
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name:
      - pve-headers
  tags:
    - apt
  when: pve_install_pve_headers

- name: Remove sysctl config from deprecated config location.
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "absent"
  with_items: "{{ pve_sysctl }}"
  tags:
    - sysctl

- name: Configure sysctl.
  ansible.posix.sysctl:
    sysctl_file: "/etc/sysctl.d/01-proxmox.conf"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ pve_sysctl }}"
  tags:
    - sysctl

- name: Download templates.
  ansible.builtin.command: "pveam download local {{ item }}"
  args:
    creates: /var/lib/vz/template/cache/{{ item }}
  with_items: "{{ pve_templates }}"
  tags:
    - templates

- name: Configure vzdump.
  ansible.builtin.include_tasks: vzdump.yml
  tags:
    - vzdump

- name: Configure fstrim.
  ansible.builtin.include_tasks: fstrim.yml
  tags:
    - fstrim

- name: Configure lxc.
  ansible.builtin.include_tasks: lxc_config.yml
  tags:
    - lxc_config
  with_items: "{{ pve_lxc_config }}"

- name: Enable backports.
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/backports.list
    content: |
      deb http://ftp.de.debian.org/debian {{ ansible_distribution_release }}-backports main
    mode: "0644"
  tags:
    - apt
  when: pve_enable_backports

- name: Configure resolv.conf.
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: |
      # managed by Ansible tobias_richter.proxmox role
      domain {{ pve_dns_domain }}
      search {{ pve_dns_domain }}
      {% if pve_nameserver | type_debug == 'list' %}
        {%- for nameserver in pve_nameserver -%}nameserver {{ nameserver }}
      {% endfor %}
      {% else %}
      nameserver {{ pve_nameserver }}      
      {% endif %}

    mode: "0644"
  tags:
    - resolv

- name: Configure influxdb.
  when:
    - pve_influxdb_port is defined
    - pve_influxdb_host is defined
  tags:
    - influxdb
  block:

    - name: Touch influxdb status.cfg first.
      ansible.builtin.file:
        path: /etc/pve/status.cfg
        state: touch
        mode: "0644"
      changed_when: false

    - name: Configure influxdb in status.cfg
      ansible.builtin.copy:
        dest: /etc/pve/status.cfg
        content: |
          # managed by Ansible tobias_richter.proxmox role
          influxdb:
            server {{ pve_influxdb_host }}
            port {{ pve_influxdb_port }}
        mode: "0644"

- name: Enable kernel module.
  community.general.modprobe:
    name: "{{ kernel_module }}"
    state: present
  register: pve__register_module_enabled
  until: pve__register_module_enabled is succeeded
  retries: 10
  delay: 10
  failed_when: pve__register_module_enabled is failure
  with_items: "{{ pve_kernel_modules_present }}"
  loop_control:
    loop_var: kernel_module
  tags:
    - module

- name: "Enable kernel module in at boot"
  ansible.builtin.blockinfile:
    path: "/etc/modules-load.d/modules.conf"
    marker: "# {mark} managed by tobias_richter.proxmox - module: {{ kernel_module }}"
    block: "{{ kernel_module }}"
  with_items: "{{ pve_kernel_modules_present }}"
  loop_control:
    loop_var: kernel_module
  tags:
    - module
