name: CI

env:
  ROLE_NAME: python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: lint & syntax check

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      
      - name: Cache PIP
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install role requirements
        uses: BSFishy/pip-action@v1
        with:
          requirements: "requirements.txt"

      - name: Create ansible.cfg
        run: "printf '[defaults]\nroles_path=./tests/requirements/:../' > ansible.cfg"

      - name: ansible-playbook syntax check
        uses: dawidd6/action-ansible-playbook@61ed42d89cb3f2582d37d71ee7e9e61f52e877ec
        with:
          playbook: tests/test.yml
          directory: "."
          requirements: tests/requirements.yml
          options: --syntax-check -i tests/inventory

      - name: ansible-lint
        uses:  ansible/ansible-lint@v24.7.0

  import:
    name: import
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a new import on Galaxy.
        uses: robertdebock/galaxy-action@1.2.1
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}


